#!/usr/bin/env bash

## Copyright (C) 2020-2021 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3

## This script will download and build AUR pkgs.

## ANSI Colors (FG & BG)
RED="$(printf '\033[31m')"  GREEN="$(printf '\033[32m')"  ORANGE="$(printf '\033[33m')"  BLUE="$(printf '\033[34m')"
MAGENTA="$(printf '\033[35m')"  CYAN="$(printf '\033[36m')"  WHITE="$(printf '\033[37m')" BLACK="$(printf '\033[30m')"

## Packages
DIR="$(pwd)"
PKGDIR="$DIR/packages_aur"

LIST=(mpdris2
    nemo-ext-git-git
    nemo-meld-compare
    shellcheck-bin
    xorg-font-utils
    bashmount
    authy
    font-manager-git
    lf-bin
	  )

## Reset terminal colors
reset_color() {
	tput sgr0   # reset attributes
	tput op     # reset color
    return
}

PKGS=(`for i in "${LIST[@]}"; do echo $i; done | sort`)
_pkgs=()

# Download AUR packages
download_pkgs () {
	for pkg in "${PKGS[@]}"; do
		git clone --depth 1 https://aur.archlinux.org/${pkg}.git	
    done
}

download_pkgs

